services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    networks:
      - caddy
      - default
    labels:
      caddy: stac-semantic-search.labs.sunu.in
      caddy.reverse_proxy: "{{upstreams 8000}}"
    command: uvicorn stac_search.api:app --host 0.0.0.0 --port 8000 --reload

networks:
  caddy:
    external: true
