{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "stac-search.fullname" . }}
  labels:
    {{- include "stac-search.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if or .Values.ingress.tls .Values.ingress.api.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
    {{- if .Values.ingress.api.enabled }}
    {{- range .Values.ingress.api.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                {{- if eq .service "api" }}
                name: {{ include "stac-search.api.serviceName" $ }}
                port:
                  number: {{ $.Values.api.service.port }}
                {{- else if eq .service "frontend" }}
                name: {{ include "stac-search.frontend.serviceName" $ }}
                port:
                  number: {{ $.Values.frontend.service.port }}
                {{- end }}
          {{- end }}
    {{- end }}
    {{- if .Values.ingress.api.enabled }}
    {{- range .Values.ingress.api.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "stac-search.api.serviceName" $ }}
                port:
                  number: {{ $.Values.api.service.port }}
          {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
