{{/*
This template creates a Kubernetes Secret for the API container.
Secrets defined in .Values.api.secrets will be loaded as environment variables
in both the init container and main API container.

Usage in values.yaml:
api:
  secrets:
    OPENAI_API_KEY: "your-api-key-here"
    OTHER_SECRET: "another-secret-value"

Only secrets with non-empty values will be included in the Secret object.
*/}}
{{- if .Values.api.secrets }}
{{- $hasSecrets := false }}
{{- range $key, $value := .Values.api.secrets }}
{{- if $value }}
{{- $hasSecrets = true }}
{{- end }}
{{- end }}
{{- if $hasSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stac-search.fullname" . }}-api-secrets
  labels:
    {{- include "stac-search.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
type: Opaque
data:
  {{- range $key, $value := .Values.api.secrets }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
