---
# API Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stac-search.api.serviceName" . }}
  labels:
    {{- include "stac-search.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "stac-search.api.selectorLabels" . | nindent 4 }}

---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stac-search.frontend.serviceName" . }}
  labels:
    {{- include "stac-search.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "stac-search.frontend.selectorLabels" . | nindent 4 }}
