name: Publish Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'helm-chart/**'
  release:
    types: [published]

jobs:
  publish-helm-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.13.0'

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm chart
        run: |
          helm package helm/stac-semantic-search --destination ./chart-packages

      - name: Push Helm chart to GHCR
        run: |
          helm push ./chart-packages/*.tgz oci://ghcr.io/developmentseed/stac-semantic-search/helm-chart

      - name: List packaged charts
        run: |
          ls -la ./chart-packages/
